// AUTO-GENERATED by docs/scripts/generate-docs.ts
// Do not edit manually — run: npx tsx docs/scripts/generate-docs.ts

export interface ComponentProp {
  name: string;
  type: string;
  required: boolean;
  default?: string;
  description: string;
}

export interface ComponentDoc {
  name: string;
  description: string;
  props: ComponentProp[];
  examples: string[];
}

export interface Package {
  slug: string;
  name: string;
  title: string;
  description: string;
  category: string;
  operator?: string;
  operatorVersion?: string;
  keywords: string[];
  components: ComponentDoc[];
}

export const packages: Package[] = [
  {
    slug: "cert-manager",
    name: "@r8s/cert-manager",
    title: "cert-manager",
    description: "TLS certificate automation components for Kubernetes. Declares the cert-manager operator and provides Let's Encrypt issuers and managed certificates.",
    category: "Security & Identity",
    operator: "certManager",
    operatorVersion: "1.14.0",
    keywords: ["cert-manager", "tls", "certificate", "letsencrypt", "acme", "cluster-issuer", "security"],
    components: [
      {
        name: "LetsEncryptIssuer",
        description: "",
        props: [
      { name: "name", type: "string", required: true, description: "" },
      { name: "email", type: "string", required: true, description: "" },
      { name: "server", type: "'production' | 'staging'", required: false, description: "" },
      { name: "ingressClass", type: "string", required: false, description: "" },
        ],
        examples: [],
      },
      {
        name: "LetsEncryptIssuer",
        description: "",
        props: [
        ],
        examples: [],
      },
      {
        name: "ManagedCertificate",
        description: "",
        props: [
      { name: "name", type: "string", required: true, description: "" },
      { name: "namespace", type: "string", required: false, description: "" },
      { name: "secretName", type: "string", required: true, description: "" },
      { name: "issuerName", type: "string", required: true, description: "" },
      { name: "dnsNames", type: "string[]", required: true, description: "" },
      { name: "duration", type: "string", required: false, description: "" },
      { name: "renewBefore", type: "string", required: false, description: "" },
        ],
        examples: [],
      },
      {
        name: "ManagedCertificate",
        description: "",
        props: [
        ],
        examples: [],
      },
    ],
  },
  {
    slug: "clickhouse",
    name: "@r8s/clickhouse",
    title: "clickhouse",
    description: "ClickHouse OLAP database components powered by the Altinity ClickHouse Operator. Declares clickhouse-operator and provisions sharded, replicated clusters with ZooKeeper.",
    category: "Data & Analytics",
    operator: "clickhouse",
    operatorVersion: "0.23.0",
    keywords: ["clickhouse", "olap", "analytics database", "clickhouse-operator", "altinity", "data"],
    components: [
      {
        name: "ClickHouseCluster",
        description: "",
        props: [
      { name: "name", type: "string", required: true, description: "" },
      { name: "namespace", type: "string", required: false, description: "" },
      { name: "cluster", type: "{ layout?: { shardsCount?: number, replicasCount?: number } }", required: false, description: "" },
      { name: "zookeeper", type: "{ nodes?: Array }", required: false, description: "" },
      { name: "users", type: "Record", required: false, description: "" },
      { name: "profiles", type: "Record", required: false, description: "" },
      { name: "quotas", type: "Record", required: false, description: "" },
      { name: "templates", type: "{ podTemplates?: Array, volumeClaimTemplates?: Array }", required: false, description: "" },
        ],
        examples: [],
      },
      {
        name: "ClickHouseCluster",
        description: "ClickHouse cluster using ClickHouse Operator.",
        props: [
        ],
        examples: ["<ClickHouseCluster\n  name=\"analytics\"\n  namespace=\"production\"\n  cluster={{\n    layout: { shardsCount: 2, replicasCount: 2 }\n  }}\n/>"],
      },
    ],
  },
  {
    slug: "envoy",
    name: "@r8s/envoy",
    title: "envoy",
    description: "Envoy Gateway components implementing the Kubernetes Gateway API. Declares envoy-gateway and provisions Gateways, HTTPRoutes, and EnvoyProxy configurations.",
    category: "Networking",
    operator: "envoyGateway",
    operatorVersion: "1.7.0",
    keywords: ["gateway", "envoy", "envoy-gateway", "gateway api", "httproute", "ingress", "networking"],
    components: [
      {
        name: "Gateway",
        description: "",
        props: [
      { name: "name", type: "string", required: true, description: "" },
      { name: "namespace", type: "string", required: false, description: "" },
      { name: "gatewayClassName", type: "string", required: false, description: "" },
      { name: "listeners", type: "ListenerConfig[]", required: true, description: "" },
      { name: "addresses", type: "Array", required: false, description: "" },
        ],
        examples: [],
      },
      {
        name: "Gateway",
        description: "Gateway resource using Gateway API (Envoy Gateway). Requires Envoy Gateway operator to be installed.",
        props: [
        ],
        examples: ["<Gateway\n  name=\"public-gateway\"\n  namespace=\"envoy-gateway-system\"\n  gatewayClassName=\"eg\"\n  listeners={[\n    { name: 'https', protocol: 'HTTPS', port: 443, hostname: 'api.example.com' },\n  ]}\n/>"],
      },
      {
        name: "HTTPRoute",
        description: "",
        props: [
      { name: "name", type: "string", required: true, description: "" },
      { name: "namespace", type: "string", required: false, description: "" },
      { name: "parentRefs", type: "Array", required: true, description: "" },
      { name: "hostnames", type: "string[]", required: false, description: "" },
      { name: "rules", type: "Array", required: true, description: "" },
        ],
        examples: [],
      },
      {
        name: "HTTPRoute",
        description: "HTTPRoute for Gateway API routing.",
        props: [
        ],
        examples: [],
      },
      {
        name: "EnvoyProxy",
        description: "",
        props: [
      { name: "name", type: "string", required: true, description: "" },
      { name: "namespace", type: "string", required: false, description: "" },
      { name: "mergeGateways", type: "boolean", required: false, description: "" },
      { name: "serviceType", type: "'LoadBalancer' | 'NodePort' | 'ClusterIP'", required: false, description: "" },
      { name: "nodePort", type: "number", required: false, description: "" },
        ],
        examples: [],
      },
      {
        name: "EnvoyProxy",
        description: "EnvoyProxy configuration for Envoy Gateway.",
        props: [
        ],
        examples: [],
      },
    ],
  },
  {
    slug: "external-dns",
    name: "@r8s/external-dns",
    title: "external-dns",
    description: "DNS management components. Declares the external-dns operator and creates DNSEndpoint resources plus annotation helpers for ingress-based DNS routing.",
    category: "Networking",
    operator: "externalDNS",
    operatorVersion: "0.14.0",
    keywords: ["external-dns", "dns", "dnsendpoints", "networking"],
    components: [
      {
        name: "ExternalDNSRecord",
        description: "",
        props: [
      { name: "name", type: "string", required: true, description: "" },
      { name: "namespace", type: "string", required: false, description: "" },
      { name: "dnsName", type: "string", required: true, description: "" },
      { name: "targets", type: "string[]", required: true, description: "" },
      { name: "recordType", type: "string", required: false, description: "" },
      { name: "ttl", type: "number", required: false, description: "" },
        ],
        examples: [],
      },
      {
        name: "ExternalDNSRecord",
        description: "",
        props: [
        ],
        examples: [],
      },
      {
        name: "ExternalDNSIngressAnnotation",
        description: "",
        props: [
      { name: "domain", type: "string", required: true, description: "" },
      { name: "targets", type: "string[]", required: true, description: "" },
        ],
        examples: [],
      },
    ],
  },
  {
    slug: "keycloak",
    name: "@r8s/keycloak",
    title: "keycloak",
    description: "Identity and access management components powered by the Keycloak Operator. Declares keycloak-operator and provisions Keycloak instances and realm imports.",
    category: "Security & Identity",
    operator: "keycloak",
    operatorVersion: "24.0.0",
    keywords: ["keycloak", "iam", "sso", "oauth", "openid", "identity", "security"],
    components: [
      {
        name: "KeycloakInstance",
        description: "",
        props: [
      { name: "name", type: "string", required: true, description: "" },
      { name: "namespace", type: "string", required: false, description: "" },
      { name: "hostname", type: "string", required: true, description: "" },
      { name: "instances", type: "number", required: false, description: "" },
      { name: "tlsSecretName", type: "string", required: false, description: "" },
      { name: "dbHost", type: "string", required: false, description: "" },
      { name: "dbName", type: "string", required: false, description: "" },
      { name: "dbUsernameSecret", type: "{ name: string, key: string }", required: false, description: "" },
      { name: "dbPasswordSecret", type: "{ name: string, key: string }", required: false, description: "" },
      { name: "ingressClassName", type: "string", required: false, description: "" },
        ],
        examples: [],
      },
      {
        name: "KeycloakInstance",
        description: "Keycloak identity provider with automatic database wiring. When placed inside a Database component, it auto-connects: <Database name=\"keycloak-db\" storage=\"10Gi\"> <KeycloakInstance name=\"keycloak\" hostname=\"auth.example.com\" /> </Database> Or provide explicit dbHost for external databases: <KeycloakInstance name=\"keycloak\" hostname=\"auth.example.com\" dbHost=\"my-db-rw\" />",
        props: [
        ],
        examples: [],
      },
      {
        name: "KeycloakRealm",
        description: "",
        props: [
      { name: "name", type: "string", required: true, description: "" },
      { name: "namespace", type: "string", required: true, description: "" },
      { name: "keycloakName", type: "string", required: true, description: "" },
      { name: "realmName", type: "string", required: true, description: "" },
      { name: "displayName", type: "string", required: false, description: "" },
      { name: "clients", type: "Array", required: false, description: "" },
      { name: "users", type: "Array", required: false, description: "" },
        ],
        examples: [],
      },
      {
        name: "KeycloakRealm",
        description: "",
        props: [
        ],
        examples: [],
      },
    ],
  },
  {
    slug: "logging-operator",
    name: "@r8s/logging-operator",
    title: "logging-operator",
    description: "Log aggregation components powered by Banzai Cloud's Logging Operator. Declares logging-operator and provisions Logging, Flow, and Output resources.",
    category: "Observability",
    operator: "logging",
    operatorVersion: "4.2.3",
    keywords: ["logging", "logs", "fluentd", "fluentbit", "banzai", "logging-operator", "observability"],
    components: [
      {
        name: "Logging",
        description: "",
        props: [
      { name: "name", type: "string", required: true, description: "" },
      { name: "namespace", type: "string", required: false, description: "" },
      { name: "fluentd", type: "{ replicas?: number, resources?: { requests?: { cpu?: string, memory?: string }, limits?: { cpu?: string, memory?: string } } }", required: false, description: "" },
      { name: "fluentbit", type: "{ resources?: { requests?: { cpu?: string, memory?: string }, limits?: { cpu?: string, memory?: string } } }", required: false, description: "" },
      { name: "controlNamespace", type: "string", required: false, description: "" },
        ],
        examples: [],
      },
      {
        name: "Logging",
        description: "Logging resource using Logging Operator.",
        props: [
        ],
        examples: ["<Logging\n  name=\"platform-logs\"\n  namespace=\"logging\"\n  fluentd={{ replicas: 2 }}\n/>"],
      },
      {
        name: "Flow",
        description: "",
        props: [
      { name: "name", type: "string", required: true, description: "" },
      { name: "namespace", type: "string", required: false, description: "" },
      { name: "match", type: "Array", required: false, description: "" },
      { name: "filters", type: "Array", required: false, description: "" },
      { name: "outputRefs", type: "string[]", required: true, description: "" },
        ],
        examples: [],
      },
      {
        name: "Flow",
        description: "Flow for routing logs to outputs.",
        props: [
        ],
        examples: [],
      },
      {
        name: "Output",
        description: "",
        props: [
      { name: "name", type: "string", required: true, description: "" },
      { name: "namespace", type: "string", required: false, description: "" },
      { name: "loki", type: "{ url: string, configureKubernetesLabels?: boolean, labels?: Record }", required: false, description: "" },
      { name: "s3", type: "{ bucket: string, region: string, path: string }", required: false, description: "" },
        ],
        examples: [],
      },
      {
        name: "Output",
        description: "Output destination for logs.",
        props: [
        ],
        examples: [],
      },
    ],
  },
  {
    slug: "loki",
    name: "@r8s/loki",
    title: "loki",
    description: "Loki log aggregation stack components. Declares the loki operator and provisions LokiStack and AlertingRule resources.",
    category: "Observability",
    operator: "loki",
    operatorVersion: "5.47.0",
    keywords: ["loki", "logs", "log aggregation", "grafana", "observability"],
    components: [
      {
        name: "LokiStack",
        description: "",
        props: [
      { name: "name", type: "string", required: true, description: "" },
      { name: "namespace", type: "string", required: false, description: "" },
      { name: "storage", type: "{ type: 's3' | 'gcs' | 'azure' | 'filesystem', bucket?: string, region?: string, endpoint?: string }", required: false, description: "" },
      { name: "replication", type: "{ factor?: number }", required: false, description: "" },
      { name: "limits", type: "{ ingestion?: { rate?: string, burstSize?: string }, retention?: { period?: string } }", required: false, description: "" },
      { name: "resources", type: "{ requests?: { cpu?: string, memory?: string }, limits?: { cpu?: string, memory?: string } }", required: false, description: "" },
        ],
        examples: [],
      },
      {
        name: "LokiStack",
        description: "LokiStack for log aggregation.",
        props: [
        ],
        examples: ["<LokiStack\n  name=\"loki\"\n  namespace=\"loki\"\n  storage={{ type: 's3', bucket: 'my-loki-bucket', region: 'eu-north-1' }}\n/>"],
      },
      {
        name: "AlertingRule",
        description: "",
        props: [
      { name: "name", type: "string", required: true, description: "" },
      { name: "namespace", type: "string", required: false, description: "" },
      { name: "groups", type: "Array", required: true, description: "" },
        ],
        examples: [],
      },
      {
        name: "AlertingRule",
        description: "AlertingRule for Loki-based alerting.",
        props: [
        ],
        examples: [],
      },
    ],
  },
  {
    slug: "openbao",
    name: "@r8s/openbao",
    title: "openbao",
    description: "Secret management components powered by the Vault Secrets Operator (OpenBao fork). Declares vault-secrets-operator and provisions VaultConnection, VaultAuth, and VaultStaticSecret resources.",
    category: "Security & Identity",
    operator: "vaultSecrets",
    operatorVersion: "0.5.0",
    keywords: ["openbao", "vault", "secrets", "vault-secrets-operator", "security"],
    components: [
      {
        name: "VaultConnection",
        description: "",
        props: [
      { name: "name", type: "string", required: true, description: "" },
      { name: "namespace", type: "string", required: false, description: "" },
      { name: "address", type: "string", required: true, description: "" },
      { name: "caCertSecretRef", type: "string", required: false, description: "" },
      { name: "skipTLSVerify", type: "boolean", required: false, description: "" },
        ],
        examples: [],
      },
      {
        name: "VaultConnectionConfig",
        description: "",
        props: [
        ],
        examples: [],
      },
      {
        name: "VaultKubernetesAuth",
        description: "",
        props: [
      { name: "name", type: "string", required: true, description: "" },
      { name: "namespace", type: "string", required: true, description: "" },
      { name: "vaultConnectionRef", type: "string", required: false, description: "" },
      { name: "role", type: "string", required: true, description: "" },
      { name: "serviceAccount", type: "string", required: true, description: "" },
      { name: "mount", type: "string", required: false, description: "" },
        ],
        examples: [],
      },
      {
        name: "VaultKubernetesAuth",
        description: "",
        props: [
        ],
        examples: [],
      },
      {
        name: "VaultDatabaseSecret",
        description: "",
        props: [
      { name: "name", type: "string", required: true, description: "" },
      { name: "namespace", type: "string", required: true, description: "" },
      { name: "vaultAuthRef", type: "string", required: true, description: "" },
      { name: "mount", type: "string", required: true, description: "" },
      { name: "path", type: "string", required: true, description: "" },
      { name: "secretName", type: "string", required: true, description: "" },
      { name: "rolloutRestartTarget", type: "{ kind: string, name: string }", required: false, description: "" },
        ],
        examples: [],
      },
      {
        name: "VaultDatabaseSecret",
        description: "",
        props: [
        ],
        examples: [],
      },
      {
        name: "VaultKVSecret",
        description: "",
        props: [
      { name: "name", type: "string", required: true, description: "" },
      { name: "namespace", type: "string", required: true, description: "" },
      { name: "vaultAuthRef", type: "string", required: true, description: "" },
      { name: "mount", type: "string", required: true, description: "" },
      { name: "path", type: "string", required: true, description: "" },
      { name: "secretName", type: "string", required: true, description: "" },
      { name: "type", type: "'kv-v1' | 'kv-v2'", required: false, description: "" },
      { name: "rolloutRestartTarget", type: "{ kind: string, name: string }", required: false, description: "" },
        ],
        examples: [],
      },
      {
        name: "VaultKVSecret",
        description: "",
        props: [
        ],
        examples: [],
      },
    ],
  },
  {
    slug: "prometheus",
    name: "@r8s/prometheus",
    title: "prometheus",
    description: "Prometheus stack components powered by kube-prometheus-stack. Declares the prometheus operator and provides ServiceMonitors, PrometheusRules, and PodMonitors.",
    category: "Observability",
    operator: "prometheus",
    operatorVersion: "0.72.0",
    keywords: ["monitoring", "prometheus", "grafana", "alertmanager", "servicemonitor", "podmonitor", "observability"],
    components: [
      {
        name: "ServiceMonitor",
        description: "",
        props: [
      { name: "name", type: "string", required: true, description: "" },
      { name: "namespace", type: "string", required: false, description: "" },
      { name: "labels", type: "Record", required: false, description: "" },
      { name: "selector", type: "{ matchLabels: Record }", required: true, description: "" },
      { name: "endpoints", type: "Array", required: true, description: "" },
        ],
        examples: [],
      },
      {
        name: "ServiceMonitor",
        description: "ServiceMonitor for Prometheus scraping. Requires Prometheus Operator to be installed.",
        props: [
        ],
        examples: ["<ServiceMonitor\n  name=\"api-metrics\"\n  namespace=\"production\"\n  selector={{ matchLabels: { app: 'api' } }}\n  endpoints={[{ port: 'metrics', path: '/metrics' }]}\n/>"],
      },
      {
        name: "PrometheusRule",
        description: "",
        props: [
      { name: "name", type: "string", required: true, description: "" },
      { name: "namespace", type: "string", required: false, description: "" },
      { name: "groups", type: "Array", required: true, description: "" },
        ],
        examples: [],
      },
      {
        name: "PrometheusRule",
        description: "PrometheusRule for alerting rules.",
        props: [
        ],
        examples: [],
      },
      {
        name: "PodMonitor",
        description: "",
        props: [
      { name: "name", type: "string", required: true, description: "" },
      { name: "namespace", type: "string", required: false, description: "" },
      { name: "labels", type: "Record", required: false, description: "" },
      { name: "selector", type: "{ matchLabels: Record }", required: true, description: "" },
      { name: "podMetricsEndpoints", type: "Array", required: true, description: "" },
        ],
        examples: [],
      },
      {
        name: "PodMonitor",
        description: "PodMonitor for scraping pods directly (without Service).",
        props: [
        ],
        examples: [],
      },
    ],
  },
  {
    slug: "redis",
    name: "@r8s/redis",
    title: "redis",
    description: "Redis cluster and replication components powered by the Redis Operator. Declares redis-operator and provisions RedisCluster and RedisReplication resources.",
    category: "Data & Analytics",
    operator: "redis",
    operatorVersion: "0.22.0",
    keywords: ["redis", "cache", "redis-operator", "data", "cluster"],
    components: [
      {
        name: "RedisCluster",
        description: "",
        props: [
      { name: "name", type: "string", required: true, description: "" },
      { name: "namespace", type: "string", required: false, description: "" },
      { name: "clusterSize", type: "number", required: false, description: "" },
      { name: "redisExporter", type: "boolean", required: false, description: "" },
      { name: "storage", type: "string", required: false, description: "" },
      { name: "storageClassName", type: "string", required: false, description: "" },
      { name: "redisSecret", type: "{ name: string, key: string }", required: false, description: "" },
      { name: "resources", type: "{ limits?: { cpu?: string, memory?: string }, requests?: { cpu?: string, memory?: string } }", required: false, description: "" },
        ],
        examples: [],
      },
      {
        name: "RedisCluster",
        description: "Redis Cluster using OT-Container-Kit Redis Operator. Declares redis-operator dependency automatically.",
        props: [
        ],
        examples: ["<RedisCluster\n  name=\"cache\"\n  namespace=\"production\"\n  clusterSize={3}\n  storage=\"10Gi\"\n/>"],
      },
      {
        name: "RedisReplication",
        description: "",
        props: [
      { name: "name", type: "string", required: true, description: "" },
      { name: "namespace", type: "string", required: false, description: "" },
      { name: "clusterSize", type: "number", required: false, description: "" },
      { name: "redisExporter", type: "boolean", required: false, description: "" },
      { name: "storage", type: "string", required: false, description: "" },
      { name: "storageClassName", type: "string", required: false, description: "" },
        ],
        examples: [],
      },
      {
        name: "RedisReplication",
        description: "Redis Replication (master-replica) using Redis Operator.",
        props: [
        ],
        examples: [],
      },
    ],
  },
];

export function getPackageCategories(): string[] {
  return [...new Set(packages.map(p => p.category))].sort();
}

export function getPackageBySlug(slug: string): Package | undefined {
  return packages.find(p => p.slug === slug);
}
